create table organizations (
    id bigint generated by default as identity,
    created_at timestamp(6),
    category varchar(255) not null check (category in ('SUPERMARKET','PHARMACY','RESTAURANT','RETAIL_CLOTHING','GENERAL_TRADE','COMPANY_OTHER')),
    name varchar(255) not null,
    primary key (id)
);

create table branches (
    id bigint generated by default as identity,
    organization_id bigint not null,
    active boolean not null,
    city varchar(255),
    name varchar(255) not null,
    primary key (id)
);

create table app_users (
    id bigint generated by default as identity,
    active boolean not null,
    branch_id bigint,
    organization_id bigint,
    created_at timestamp(6),
    tos_accepted_at timestamp(6),
    email varchar(255) not null unique,
    name varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null check (role in ('OWNER','BRANCH_MANAGER','STAFF','PLATFORM_ADMIN')),
    primary key (id)
);

create table items (
    id bigint generated by default as identity,
    branch_id bigint not null,
    cost_price float(53) not null,
    expiry_date date,
    last_sale_date date,
    quantity float(53) not null,
    sale_price float(53) not null,
    movement_status varchar(255) check (movement_status in ('FAST','MEDIUM','SLOW','STAGNANT')),
    name varchar(255) not null,
    sub_category varchar(255),
    primary key (id)
);

create table daily_entries (
    id bigint generated by default as identity,
    branch_id bigint not null,
    available_liquidity float(53) not null,
    entry_date date not null,
    payables float(53) not null,
    receivables float(53) not null,
    total_cogs float(53) not null,
    total_profit float(53) not null,
    total_sales float(53) not null,
    primary key (id),
    unique (branch_id, entry_date)
);

create table purchases (
    id bigint generated by default as identity,
    branch_id bigint not null,
    item_id bigint,
    cost_price float(53) not null,
    purchase_date date not null,
    quantity float(53) not null,
    supplier_name varchar(255) not null,
    primary key (id)
);

create table recommendations (
    id bigint generated by default as identity,
    branch_id bigint not null,
    item_id bigint,
    expected_value float(53) not null,
    created_at timestamp(6),
    resolved_at timestamp(6),
    priority varchar(255) not null check (priority in ('HIGH','MEDIUM','LOW')),
    status varchar(255) check (status in ('OPEN','APPLIED','DISMISSED')),
    title varchar(255) not null,
    type varchar(255) not null check (type in ('STOP_PURCHASE','INCREASE_ORDER','ADJUST_PRICE','PROMOTION_CAMPAIGN','LIQUIDITY_ALERT','EXPIRY_ALERT')),
    primary key (id)
);

create table health_score_history (
    id bigint generated by default as identity,
    branch_id bigint not null,
    inventory_score float(53) not null,
    liquidity_score float(53) not null,
    pricing_score float(53) not null,
    profit_score float(53) not null,
    purchases_score float(53) not null,
    sales_score float(53) not null,
    score_date date not null,
    total_score float(53) not null,
    primary key (id)
);

create table category_benchmarks (
    category varchar(255) not null check (category in ('SUPERMARKET','PHARMACY','RESTAURANT','RETAIL_CLOTHING','GENERAL_TRADE','COMPANY_OTHER')),
    inventory_coverage_max_months float(53) not null,
    inventory_coverage_min_months float(53) not null,
    liquidity_ratio_max float(53) not null,
    liquidity_ratio_min float(53) not null,
    medium_moving_days_threshold integer not null,
    slow_moving_days_threshold integer not null,
    stagnation_days_threshold integer not null,
    target_margin_percent float(53) not null,
    weight_inventory float(53) not null,
    weight_liquidity float(53) not null,
    weight_pricing float(53) not null,
    weight_profit float(53) not null,
    weight_purchases float(53) not null,
    weight_sales float(53) not null,
    primary key (category)
);

create table group_orders (
    id bigint generated by default as identity,
    current_quantity float(53) not null,
    estimated_market_price float(53) not null,
    negotiated_price float(53),
    target_quantity float(53) not null,
    created_at timestamp(6),
    item_name varchar(255) not null,
    status varchar(255) not null check (status in ('COLLECTING','NEGOTIATED','DISTRIBUTED','CANCELLED')),
    primary key (id)
);

create table group_order_participants (
    id bigint generated by default as identity,
    group_order_id bigint not null,
    organization_id bigint not null,
    quantity float(53) not null,
    primary key (id)
);

create table password_reset_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    used boolean not null,
    expires_at timestamp(6) not null,
    token varchar(255) not null unique,
    primary key (id)
);

create table refresh_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    revoked boolean not null,
    expires_at timestamp(6) not null,
    token varchar(255) not null unique,
    primary key (id)
);

create table audit_logs (
    id bigint generated by default as identity,
    organization_id bigint,
    created_at timestamp(6) not null,
    details varchar(1000),
    action varchar(255) not null,
    actor_email varchar(255),
    entity_id varchar(255),
    entity_type varchar(255),
    primary key (id)
);

create table notifications (
    id bigint generated by default as identity,
    organization_id bigint not null,
    created_at timestamp(6) not null,
    read_at timestamp(6),
    message varchar(500) not null,
    severity varchar(255) not null check (severity in ('INFO','SUCCESS','WARNING')),
    title varchar(255) not null,
    primary key (id)
);

alter table branches add constraint fk_branches_organization foreign key (organization_id) references organizations;
alter table app_users add constraint fk_users_branch foreign key (branch_id) references branches;
alter table app_users add constraint fk_users_organization foreign key (organization_id) references organizations;
alter table items add constraint fk_items_branch foreign key (branch_id) references branches;
alter table daily_entries add constraint fk_daily_entries_branch foreign key (branch_id) references branches;
alter table purchases add constraint fk_purchases_branch foreign key (branch_id) references branches;
alter table purchases add constraint fk_purchases_item foreign key (item_id) references items;
alter table recommendations add constraint fk_recommendations_branch foreign key (branch_id) references branches;
alter table recommendations add constraint fk_recommendations_item foreign key (item_id) references items;
alter table health_score_history add constraint fk_health_score_history_branch foreign key (branch_id) references branches;
alter table group_order_participants add constraint fk_participants_group_order foreign key (group_order_id) references group_orders;
alter table group_order_participants add constraint fk_participants_organization foreign key (organization_id) references organizations;
alter table password_reset_tokens add constraint fk_password_reset_tokens_user foreign key (user_id) references app_users;
alter table refresh_tokens add constraint fk_refresh_tokens_user foreign key (user_id) references app_users;

-- فهارس على أعمدة المفاتيح الأجنبية والاستعلامات الشائعة (Postgres لا يُنشئ فهارس تلقائية على FK)
create index idx_branches_organization on branches (organization_id);
create index idx_users_branch on app_users (branch_id);
create index idx_users_organization on app_users (organization_id);
create index idx_items_branch on items (branch_id);
create index idx_purchases_branch on purchases (branch_id);
create index idx_purchases_item on purchases (item_id);
create index idx_recommendations_branch_status on recommendations (branch_id, status);
create index idx_recommendations_item on recommendations (item_id);
create index idx_health_score_history_branch_date on health_score_history (branch_id, score_date);
create index idx_group_order_participants_group_order on group_order_participants (group_order_id);
create index idx_group_order_participants_organization on group_order_participants (organization_id);
create index idx_password_reset_tokens_user on password_reset_tokens (user_id);
create index idx_refresh_tokens_user on refresh_tokens (user_id);
create index idx_audit_logs_organization_created on audit_logs (organization_id, created_at desc);
create index idx_notifications_organization_created on notifications (organization_id, created_at desc);
