create table suppliers (
    id bigint generated by default as identity,
    organization_id bigint not null,
    credit_terms_days integer not null,
    lead_time_days integer not null,
    rating float(53) not null,
    created_at timestamp(6),
    contact_info varchar(255),
    name varchar(255) not null,
    primary key (id)
);

alter table items add column supplier_id bigint;
alter table items add column safety_stock_days integer not null default 3;

create table decisions (
    id bigint generated by default as identity,
    approved_quantity double precision,
    branch_id bigint not null,
    confidence_score float(53) not null,
    financial_impact float(53) not null,
    item_id bigint not null,
    suggested_quantity float(53) not null,
    supplier_id bigint,
    created_at timestamp(6),
    outcome_recorded_at timestamp(6),
    resolved_at timestamp(6),
    actual_outcome varchar(255),
    status varchar(255) check (status in ('OPEN','APPROVED','MODIFIED','DEFERRED','DISMISSED')),
    type varchar(255) not null check (type in ('PURCHASE_ORDER')),
    reason_summary varchar(1000) not null,
    primary key (id)
);

alter table suppliers add constraint fk_suppliers_organization foreign key (organization_id) references organizations;
alter table items add constraint fk_items_supplier foreign key (supplier_id) references suppliers;
alter table decisions add constraint fk_decisions_branch foreign key (branch_id) references branches;
alter table decisions add constraint fk_decisions_item foreign key (item_id) references items;
alter table decisions add constraint fk_decisions_supplier foreign key (supplier_id) references suppliers;

create index idx_suppliers_organization on suppliers (organization_id);
create index idx_items_supplier on items (supplier_id);
create index idx_decisions_branch_status on decisions (branch_id, status);
create index idx_decisions_item on decisions (item_id);
create index idx_decisions_supplier on decisions (supplier_id);
