create table goals (
    id bigint generated by default as identity,
    organization_id bigint not null,
    priority integer not null,
    type varchar(255) not null check (type in (
        'INCREASE_PROFITABILITY','IMPROVE_LIQUIDITY','PREVENT_STOCKOUTS','REDUCE_STAGNANT_INVENTORY',
        'INCREASE_SALES','IMPROVE_SUPPLIER_PERFORMANCE','INCREASE_INVENTORY_TURNOVER'
    )),
    primary key (id),
    unique (organization_id, type)
);

alter table goals add constraint fk_goals_organization foreign key (organization_id) references organizations;
create index idx_goals_organization on goals (organization_id);
