-- المصادر المتبقية لمؤشرات BHI الأربعة التي كانت "غير متاح":
-- الهدر، دقة الجرد، كفاءة السداد، ونسبة الدين إلى حقوق الملكية.

create table waste_records (
    id bigint generated by default as identity,
    branch_id bigint not null,
    item_id bigint not null,
    waste_date date not null,
    quantity float(53) not null,
    unit_cost float(53) not null,
    reason varchar(255) not null check (reason in ('EXPIRY','DAMAGE','THEFT','OTHER')),
    note varchar(255),
    primary key (id)
);

alter table waste_records add constraint fk_waste_records_branch foreign key (branch_id) references branches;
alter table waste_records add constraint fk_waste_records_item foreign key (item_id) references items;
create index idx_waste_records_branch_date on waste_records (branch_id, waste_date);

create table stock_counts (
    id bigint generated by default as identity,
    branch_id bigint not null,
    item_id bigint not null,
    count_date date not null,
    expected_quantity float(53) not null,
    counted_quantity float(53) not null,
    note varchar(255),
    primary key (id)
);

alter table stock_counts add constraint fk_stock_counts_branch foreign key (branch_id) references branches;
alter table stock_counts add constraint fk_stock_counts_item foreign key (item_id) references items;
create index idx_stock_counts_branch_date on stock_counts (branch_id, count_date);

-- انضباط السداد: تاريخ الاستحقاق والسداد الفعلي على كل فاتورة شراء
alter table purchases add column payment_due_date date;
alter table purchases add column paid_on_date date;

-- حقوق الملكية على مستوى المؤسسة
alter table organizations add column equity float(53);
