create table policies (
    id bigint generated by default as identity,
    organization_id bigint not null unique,
    max_purchase_liquidity_ratio float(53) not null,
    min_supplier_rating float(53) not null,
    primary key (id)
);

alter table policies add constraint fk_policies_organization foreign key (organization_id) references organizations;
