-- مؤشر صحة الأعمال (BHI) وفق النموذج المرجعي المعتمد من مدير المنتج.
-- الجدولان متفرّقان عمدًا (overrides only): الحدود والأوزان الافتراضية تعيش في
-- BhiIndicatorCode و BhiAxis، ولا يُنشأ صف هنا إلا حين يغيّر المشرف قيمة فعليًا.
-- لذلك لا يوجد أي بذر ابتدائي، وفئة نشاط جديدة تعمل فورًا بلا صفوف.

create table bhi_thresholds (
    id bigint generated by default as identity,
    category varchar(255) not null check (category in ('SUPERMARKET','PHARMACY','RESTAURANT','RETAIL_CLOTHING','GENERAL_TRADE','COMPANY_OTHER')),
    code varchar(255) not null check (code in ('NET_PROFIT_MARGIN','GROSS_PROFIT_MARGIN','OPERATING_EXPENSE_RATIO','CURRENT_RATIO','CASH_RATIO','CASH_CONVERSION_CYCLE','SALES_GROWTH','INVENTORY_TURNOVER','WASTE_RATIO','STOCK_ACCURACY','DAYS_SALES_OUTSTANDING','PAYMENT_EFFICIENCY','DEBT_TO_EQUITY')),
    weak_threshold float(53) not null,
    medium_threshold float(53) not null,
    excellent_threshold float(53) not null,
    primary key (id),
    unique (category, code)
);

create table bhi_axis_weights (
    id bigint generated by default as identity,
    category varchar(255) not null check (category in ('SUPERMARKET','PHARMACY','RESTAURANT','RETAIL_CLOTHING','GENERAL_TRADE','COMPANY_OTHER')),
    axis varchar(255) not null check (axis in ('PROFITABILITY','LIQUIDITY','OPERATIONAL_EFFICIENCY','INVENTORY_MANAGEMENT','RECEIVABLES_DEBT')),
    weight float(53) not null,
    primary key (id),
    unique (category, axis)
);
