-- المصاريف التشغيلية الشهرية لكل فرع. تفتح مؤشرَي هامش صافي الربح ونسبة المصاريف
-- في محور الربحية (وزنه 0.30 في BHI) اللذين كانا "غير متاح" لعدم وجود مصدر بيانات.
-- بنية الكمية × القيمة تحاكي جدول المصاريف في نموذج مدير المنتج حرفيًا.

create table monthly_expenses (
    id bigint generated by default as identity,
    branch_id bigint not null,
    expense_month date not null,
    category varchar(255) not null check (category in ('MANAGER_SALARY','STAFF_SALARY','ELECTRICITY','RENT','TECH_SERVICES','SUNDRIES','OTHER')),
    unit_amount float(53) not null,
    quantity integer not null,
    note varchar(255),
    primary key (id),
    unique (branch_id, expense_month, category)
);

alter table monthly_expenses add constraint fk_monthly_expenses_branch foreign key (branch_id) references branches;

create index idx_monthly_expenses_branch_month on monthly_expenses (branch_id, expense_month);
